### ISSUE TITLE
PDF generation working locally but not when hosted

### ISSUE THREAD

**Issue by jnapoleon** [weinbusch/flask-tex#1]
Hi,

I just wanted to say massive thank you for this package it's saved a lot of pain!

It works perfectly when I run my app locally on my machine. However now that i've hosted on Heroku I get errors.
see below:

![image](https://user-images.githubusercontent.com/39012113/86903500-526c9100-c107-11ea-86d9-c4c3b7f11602.png)

Just wondering if you have encounter this issue?

Thanks

John

**Comment by jnapoleon** [comment]
I've looked into it a bit further it looks like my app needs to have pdflatex installed to make it work.

I'm looking into how to do this.

Feel free to close this issue.

Thanks again for this package!

**Comment by weinbusch** [comment]
you're welcome
